name: Sync NGINX Configs to Azure

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - configs/**

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4

      - name: Azure Login (with service principal credentials)
        run: |
          az login --service-principal \
            --username "${{ secrets.AZURE_CLIENT_ID }}" \
            --password "${{ secrets.AZURE_CLIENT_SECRET }}" \
            --tenant "${{ secrets.AZURE_TENANT_ID }}"

      - name: Sync NGINX Config to Azure
        uses: kuthiala/nginx-for-azure-deploy-action@main
        # uses: nginxinc/nginx-for-azure-deploy-action@v0.4.0
        with:
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resource-group-name: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
          nginx-deployment-name: ${{ secrets.NGINX_DEPLOYMENT_NAME }}
          nginx-config-directory-path: configs/
          nginx-root-config-file: nginx.conf
          transformed-nginx-config-directory-path: /etc/nginx/
          protected-files: protected.conf
          nginx-certificates: '[{"certificateName": "myCertificate", "keyvaultSecret": "https://test-n4a-gh-action.vault.azure.net/secrets/myCertificate/189746de2de34c7f84d4ded9b425c45b", "certificateVirtualPath": "/etc/nginx/certs/server1.crt", "keyVirtualPath": "/etc/nginx/certs/server2.key" },{"certificateName": "examplecert", "keyvaultSecret": "https://test-n4a-gh-action.vault.azure.net/secrets/examplecert/7fc91bac566b49edaa903f874b9557bb", "certificateVirtualPath": "/etc/nginx/certs/server12.crt", "keyVirtualPath": "/etc/nginx/certs/server12.key" }]'
          debug: true
          nginx-deployment-location: eastus2
