name: Sync NGINX Configs to Azure

on:
  push:
    branches:
      - master
    paths:
      - configs/**

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4

      - name: Azure Login (with service principal credentials)
        run: |
          az login --service-principal \
            --username "${{ secrets.AZURE_CLIENT_ID }}" \
            --password "${{ secrets.AZURE_CLIENT_SECRET }}" \
            --tenant "${{ secrets.AZURE_TENANT_ID }}"

      - name: Sync NGINX Config to Azure
        uses: kuthiala/nginx-for-azure-deploy-action@main
        with:
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resource-group-name: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
          nginx-deployment-name: ${{ secrets.NGINX_DEPLOYMENT_NAME }}
          nginx-config-directory-path: configs/
          nginx-root-config-file: nginx.conf
          transformed-nginx-config-directory-path: /etc/nginx/
